# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" , "main-demo" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
# this currently not necessary on my machine, sdk is already downloaded, and if try to setup, it will ask for administrator permission
# or i have to add it to a group that have permission to dotnet folder, very risky, im new to security and permission stuff, might
# be for later use
# - name: Setup .NET
#   uses: actions/setup-dotnet@v4
#   with:
#     dotnet-version: 7.0.x
    - name: Print dotnet version and check if build directory exist to create
      run : |
        dotnet --version
        $buildPath = Join-Path $env:GITHUB_WORKSPACE "buildDirectory"
        echo "check if this path exist: $buildPath"
        if (Test-Path $buildPath){
          echo "build path exist no need to create"
        }else{
          echo "create new path"
          mkdir $buildPath
        }
        echo "BUILD_OUTPUT_DIRECTORY=$buildPath" >> $GITHUB_ENV
    - name: print some variable
      run: |
        echo "github workspace: $env:GITHUB_WORKSPACE"
        echo "output of build directory: $env:BUILD_OUTPUT_DIRECTORY"
        echo "finsih printing"
         
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
# - name: Test
#   run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build

    
